<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<OutputType>Library</OutputType>
		<LangVersion>8.0</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Build.Framework" Version="17.13.9" />
		<PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.13.9" />
		<Reference Include="System.Net.Http" />
		<Reference Include="System.IO.Compression.FileSystem" />
	</ItemGroup>

</Project>
